#!/bin/bash

i=0

conc[0]=50
conc[1]=100
conc[2]=250
conc[3]=500

loop[0]=200
loop[1]=100
loop[2]=40
loop[3]=20


cd ./plans
while test $i != 4
do
sed 's/_loop_/'${loop[$i]}'/g' PHP_post.jmx > ./phpTest.jmx
sed 's/_conc_/'${conc[$i]}'/g' phpTest.jmx > php_post_${conc[$i]}.jmx
rm phpTest.jmx
cd ../apache-jmeter-2.7/bin/
sh ./jmeter.sh -n -t ../../plans/php_post_${conc[$i]}.jmx -l ../../results/php/post_${conc[$i]}.jtl
i=`expr $i + 1`
cd ../../plans
done

