#!/bin/bash

conc=100
loop=100

cd ./plans
sed 's/_loop_/'${loop}'/g' JSP_readFile.jmx > ./jspTest.jmx
sed 's/_conc_/'${conc}'/g' jspTest.jmx > jsp_file_${conc}.jmx
rm jspTest.jmx
cd ../apache-jmeter-2.7/bin/
sh ./jmeter.sh -n -t ../../plans/jsp_file_${conc}.jmx -l ../../results/jsp/file_${conc}.jtl
cd ../../plans


